### ISSUE TITLE
Some bugs with python 2.7

### ISSUE THREAD

**Issue by victorsndvg** [vsoch/singularity-python#2]
Hi all,

I'm trying to use the development branch of [vsoch/singularity-python](https://github.com/vsoch/singularity-python) with sregistry and I'm getting some errors. 

I would like to post this directly in the right repository, please @vsoch, could you open the issues feature for this repository? If not, which communication channel do you prefer to post issues about this repository?

I'm running [run_client.sh](https://github.com/vsoch/singularity-python/blob/development/examples/registry/run_client.sh) example and I have Python 2.7.12 installed.  is Python 3 a requirement?

Lets go with the bugs,

* First, in this line, [L86](https://github.com/vsoch/singularity-python/blob/development/singularity/registry/client/push.py#L86) It crashes because `image` does not exist.
* Then, Calling to `$ sregistry list $IMAGE` with an existing image, I get the following error with the date:
```
...
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/client/query.py", line 213, in container_search
    datetime_object = datetime.strptime(c['add_date'], '%Y-%m-%dT%H:%M:%S.%fZ')
ValueError: time data '2017-10-13T01:47:50.824098-05:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```
* There is another error calling to: ` $ sregistry delete $IMAGE`
```
This line crashes [L54](https://github.com/vsoch/singularity-python/blob/development/singularity/registry/client/delete.py#L54) . It seems that python 3 `input` command equivalent in python 2.5 is `raw_input` . 
* Finally,  if I try to force-delete `$ sregistry delete --force $IMAGE` It returns:
```
ERROR Beep boop! Internal Server Error: 500
```

Thanks in advance!

**Comment by vsoch** [comment]
hey @victorsndvg ! I'm starting to debug the first error. For the second, could you try triggering it and then after you get the "Beep Boop" try doing:

```
docker-compose logs uwsgi
```
from the registry code folder? That should show us the error!

**Comment by vsoch** [comment]
okey doke, I was able to reproduce the error:
```
sregistry list /squashyContainers squashy
Traceback (most recent call last):
  File "/home/vanessa/anaconda3/bin/sregistry", line 11, in <module>
    load_entry_point('singularity==1.2.0', 'console_scripts', 'sregistry')()
  File "/home/vanessa/anaconda3/lib/python3.5/site-packages/singularity-1.2.0-py3.5.egg/singularity/registry/main/__init__.py", line 208, in main
    subparser=subparsers[args.command])
  File "/home/vanessa/anaconda3/lib/python3.5/site-packages/singularity-1.2.0-py3.5.egg/singularity/registry/main/ls.py", line 42, in main
    sreg.ls(query=query,args=args)
  File "/home/vanessa/anaconda3/lib/python3.5/site-packages/singularity-1.2.0-py3.5.egg/singularity/registry/client/query.py", line 63, in ls
    return self.container_search(query, across_collections=True)
  File "/home/vanessa/anaconda3/lib/python3.5/site-packages/singularity-1.2.0-py3.5.egg/singularity/registry/client/query.py", line 213, in container_search
    datetime_object = datetime.strptime(c['add_date'], '%Y-%m-%dT%H:%M:%S.%fZ')
  File "/home/vanessa/anaconda3/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/vanessa/anaconda3/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2017-10-10T07:11:06.839906-05:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

and the fix is to use dateutil's parser function instead, now with re-install

```
Containers squashy
1  vanessa/squashy	latest	Oct 10, 2017 07:11AM
```
I also fixed the missing image variable - do you want to reinstall and test and see if it works for you?

**Comment by victorsndvg** [comment]
Hi @vsoch,

Perfect, thanks! :)

I don't close this issue because there is an already non fixed bug:

* There is another error calling to: ` $ sregistry delete $IMAGE`
This line crashes [L54](https://github.com/vsoch/singularity-python/blob/development/singularity/registry/client/delete.py#L54) . It seems that python 3 `input` command equivalent in python 2.5 is `raw_input` . 
* Finally,  if I try to force-delete `$ sregistry delete --force $IMAGE` It returns:
```
ERROR Beep boop! Internal Server Error: 500
```

Thanks in advance!

**Comment by vsoch** [comment]
hey @victorsndvg  ! If you look up in the thread, I need a bit of your help to diagnose this one:

>> hey @victorsndvg ! I'm starting to debug the first error. For the second, could you try triggering it and then after you get the "Beep Boop" try doing:

```
docker-compose logs uwsgi
```
>> from the registry code folder? That should show us the error!

Thanks!

**Comment by victorsndvg** [comment]
Sorry, I didn't read the previous response :sweat_smile: 

I figure out the last lines are enought, let me know if you need more.

These are the 2 last lines of the log after `sregistry delete --force`:

```
uwsgi_1   | [pid: 49|app: 0|req: 40/40] 10.38.3.235 () {40 vars in 723 bytes} [Tue Oct 17 07:37:51 2017] DELETE /api/container/dinosaur/avocado:delicious => generated 0 bytes in 2 msecs (HTTP/1.1 301) 4 headers in 176 bytes (1 switches on core 0)
uwsgi_1   | DEBUG Request payload delete|dinosaur|20171017T12Z|avocado|delicious|
uwsgi_1   | DEBUG delete/dmljdG9yc25kdmc=/20171017T12Z
uwsgi_1   | [pid: 49|app: 0|req: 41/41] 10.38.3.235 () {36 vars in 647 bytes} [Tue Oct 17 07:37:51 2017] DELETE /api/container/dinosaur/avocado:delicious/ => generated 850 bytes in 303 msecs (HTTP/1.1 500) 4 headers in 142 bytes (1 switches on core 0)
```

Thanks!

**Comment by vsoch** [comment]
okay I've adjusted some of the url regular expressions to prevent the redirect (the first 301 above). I'm weary that we aren't seeing any report of the error, just 500 (and there are indeed errors). Could you try the following:

 - update the code, `docker-compose restart` to restart the images
 - also update singularity python from vsoch/development
 - then issue the command, do both of `docker-compose logs uwsgi` and `docker-compose logs worker` to see all server logs
 - please post all messages from the worker and uwsgi that have occurred since the call!

We should be seeing more output - it's hard to just go by 500, but we can keep trying :) It could also have something to do with parsing the timestamp, so we can look at that next (possibly that same error as we had locally!)

**Comment by victorsndvg** [comment]
Sorry, now I'm not able to login ... Probably I'm doing something wrong ...

taking a look to logs I see the following messages and a new error:
```
db_1      | 2017-10-18 07:31:04.886 UTC [80] ERROR:  relation "django_session" does not exist at character 24
db_1      | 2017-10-18 07:31:04.886 UTC [80] STATEMENT:  SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'xuxzrnbr2uh0ahuyjpwv5hsv9r0iw52l' LIMIT 1
db_1      | 2017-10-18 07:31:04.904 UTC [80] ERROR:  relation "django_session" does not exist at character 109
db_1      | 2017-10-18 07:31:04.904 UTC [80] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = 'xuxzrnbr2uh0ahuyjpwv5hsv9r0iw52l' LIMIT 21
nginx_1   | 193.144.44.171 - - [18/Oct/2017:07:31:04 +0000] "GET /login/twitter/?next=http://10.38.3.249/login/ HTTP/1.1" 500 862 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" "-"
uwsgi_1   | [pid: 49|app: 0|req: 16/16] 193.144.44.171 () {40 vars in 706 bytes} [Wed Oct 18 02:31:04 2017] GET /login/twitter/?next=http://10.38.3.249/login/ => generated 850 bytes in 375 msecs (HTTP/1.1 500) 1 headers in 78 bytes (1 switches on core 0)
nginx_1   | 193.144.44.171 - - [18/Oct/2017:07:31:04 +0000] "GET /static/img/robot_package.png HTTP/1.1" 304 0 "http://10.38.3.249/login/twitter/?next=http://10.38.3.249/login/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" "-"
```

Any suggestion?

**Comment by victorsndvg** [comment]
Hi,

recent changes in datetime/timezone are not working with python2.7.

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/sregistry", line 9, in <module>
    load_entry_point('singularity==1.2.0', 'console_scripts', 'sregistry')()
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/__init__.py", line 190, in main
    from .labels import main
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/labels.py", line 26, in <module>
    from singularity.registry.client import Client
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/client/__init__.py", line 36, in <module>
    from singularity.registry.auth import read_client_secrets
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/auth.py", line 35, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone
```

**Comment by vsoch** [comment]
hey @victorsndvg - any reason you can't use the singularity image to use singularity-python? This timezone issue is sort of infamous, and it might be easier to use singularity python (with python 3) via the singularity image vs. trying to change the whole thing to get python 2.7 support. What do you think?

**Comment by victorsndvg** [comment]
No problem, for me it's Ok. I can use the Singularity image instead a local installation.

The only concern here is that (I think) it should be explained at least in docs and also `singularity-python` should check the python version.

Is it ok for you?

**Comment by vsoch** [comment]
I added it to the docs:

https://github.com/singularityware/singularity-python/wiki/Installation

I don't have singularity python check because I can't be sure of the user's use case - they might want to use other functions and be ok with that particular one not working. But if it comes up again (and a user misses the docs) then I'll add it.

**Comment by victorsndvg** [comment]
Great! closing ...
